security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialnetworkdb
    username: socialnetwork
    password: socialnetwork
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

app.nfs.path: /tmp
